import { Shield, FileSearch, Type, Layers, Image, Binary, TrendingUp, ChevronDown, ChevronUp, StickyNote, Database } from 'lucide-react'
import { useState } from 'react'

interface Check {
  name: string
  detail: string
  severity: 'high' | 'medium' | 'low'
}

interface Algorithm {
  id: string
  name: string
  category: 'universal' | 'content'
  description: string
  checks: Check[]
}

const ALGORITHMS: Algorithm[] = [
  // ── Part I: Universal ────────────────────────────────────────────────────
  {
    id: 'metadata',
    category: 'universal',
    name: 'Metadata Analysis',
    description: 'Extracts and cross-validates all embedded PDF metadata fields to detect tampering, date manipulation, and suspicious creation toolchains.',
    checks: [
      {
        name: 'Modification Date Before Creation Date',
        detail: 'Flags documents where the modification timestamp pre-dates the creation timestamp — a physically impossible state that indicates date tampering.',
        severity: 'high',
      },
      {
        name: 'PDF Created Long After Statement Period',
        detail: 'Compares the PDF creation year against year references inside the document content. A genuine statement is generated close to its close date.',
        severity: 'high',
      },
      {
        name: 'Image Editing Software as PDF Creator',
        detail: 'Detects when Photoshop, GIMP, or similar image editors are recorded as the PDF creator — a strong sign of visual forgery.',
        severity: 'high',
      },
      {
        name: 'Suspicious PDF Creator Tool',
        detail: 'Matches the creator field against known document manipulation tools (PDFedit, SmallPDF, iLovePDF, Sejda, Canva, SodaPDF, etc.).',
        severity: 'high',
      },
      {
        name: 'Unknown or Missing Creator Metadata',
        detail: 'Records an unknown creator tool or stripped metadata — deliberate removal of provenance is common in forged documents.',
        severity: 'medium',
      },
      {
        name: 'Unusually Large Date Gap',
        detail: 'Flags a creation-to-modification gap exceeding 10 years, which is atypical for financial documents.',
        severity: 'medium',
      },
    ],
  },
  {
    id: 'fonts',
    category: 'universal',
    name: 'Font Consistency Analysis',
    description: 'Analyses font families and sizes across all pages and numeric spans to identify value-level edits where individual figures were replaced.',
    checks: [
      {
        name: 'Inconsistent Font Usage Across Pages',
        detail: 'Compares font sets page-by-page. Differing sets suggest pages from separate source documents were merged.',
        severity: 'high',
      },
      {
        name: 'Inconsistent Font Sizes in Numeric Fields',
        detail: 'Computes the dominant font size among all numeric spans. Outlier sizes (>1.5pt deviation, low frequency) indicate individually edited figures.',
        severity: 'high',
      },
      {
        name: 'Excessive Number of Distinct Fonts',
        detail: 'More than 15 distinct fonts in a single document far exceeds the 3–5 typical of a genuine bank statement, suggesting copy-paste assembly.',
        severity: 'medium',
      },
      {
        name: 'Intra-Line Font Fingerprint Mismatch',
        detail: 'For every transaction row containing a monetary amount, all spans are expected to share an identical font fingerprint (name, size, bold/italic flags, colour). A single span that deviates from the rest of its row — especially on a numeric value — indicates that specific figure was replaced after the document was generated. Suppresses sub-0.3pt size differences to avoid false positives from rounding artefacts.',
        severity: 'high',
      },
    ],
  },
  {
    id: 'text_layers',
    category: 'universal',
    name: 'Text Layer Analysis',
    description: 'Scans the PDF rendering pipeline for invisible or hidden text layers used to embed data invisible to human reviewers.',
    checks: [
      {
        name: 'Hidden Text Layer (Sub-0.5pt)',
        detail: 'Detects text spans with font size below 0.5pt — effectively invisible but machine-readable, used to pass automated OCR checks or embed tracking data.',
        severity: 'high',
      },
      {
        name: 'White-on-White Invisible Text',
        detail: 'Identifies white-coloured text (color value 0xFFFFFF) rendered on white backgrounds — content hidden from reviewers but present in the PDF byte stream.',
        severity: 'high',
      },
    ],
  },
  {
    id: 'images',
    category: 'universal',
    name: 'Image Analysis',
    description: 'Examines embedded images for resolution anomalies and artefacts that indicate logos or graphics were sourced from the web or screenshots rather than generated by a banking system.',
    checks: [
      {
        name: 'Low-Resolution Images (Copied Logo)',
        detail: "Estimates effective DPI for each embedded image relative to page width. Images below 72 DPI suggest logos were copied from a website screenshot rather than rendered by the bank's PDF generator.",
        severity: 'medium',
      },
      {
        name: 'Suspicious Micro-Images Embedded',
        detail: 'Images smaller than 50×50 pixels are artefacts of image-based text replacement or tracking pixels with no legitimate purpose in a financial document.',
        severity: 'medium',
      },
    ],
  },
  {
    id: 'structure',
    category: 'universal',
    name: 'PDF Structure Analysis',
    description: 'Inspects the raw binary structure of the PDF file for revision markers, scripts, and editable form fields that are inconsistent with bank-generated documents.',
    checks: [
      {
        name: 'No Text Layer — Image-Only PDF',
        detail: 'Genuine bank statements are digitally generated and always contain a searchable text layer. An image-only PDF suggests the document was printed and re-scanned to erase digital metadata and editing traces.',
        severity: 'high',
      },
      {
        name: 'Multiple Document Revisions (%%EOF count)',
        detail: 'Counts %%EOF markers in the raw PDF byte stream. Each additional marker represents an incremental save — i.e., a post-creation edit. Genuine statements are written once.',
        severity: 'high',
      },
      {
        name: 'JavaScript Embedded in PDF',
        detail: 'Detects /JavaScript and /JS objects. Financial documents never require scripts; their presence may indicate viewer manipulation or data exfiltration attempts.',
        severity: 'high',
      },
      {
        name: 'Editable Form Fields (AcroForm)',
        detail: 'Detects /AcroForm objects. Bank statements are read-only; fillable form fields suggest the document was designed for manual value entry.',
        severity: 'medium',
      },
    ],
  },
  {
    id: 'annotations',
    category: 'universal',
    name: 'Annotation / Whitebox Overlay Analysis',
    description: 'Detects opaque white rectangle annotations and FreeText overlays used to cover original text and paste replacement values — the digital equivalent of correction fluid.',
    checks: [
      {
        name: 'White Rectangle Annotations (Whiteout Boxes)',
        detail: 'Scans all PDF annotation objects for Square/Rectangle annotations filled with white (RGB 1,1,1). These are placed over original figures and covered with new text — leaving a forensic trace in the annotation stream even when visually indistinguishable.',
        severity: 'high',
      },
      {
        name: 'Numeric Values in PDF Annotations',
        detail: 'FreeText annotations containing monetary amounts (e.g. "12,500.00") sit outside the main content stream. Their presence proves values were added after the document was generated rather than by the original system.',
        severity: 'high',
      },
    ],
  },

  // ── Part II: Content-Based ────────────────────────────────────────────────
  {
    id: 'financial',
    category: 'content',
    name: 'Financial Content Analysis',
    description: 'Heuristic analysis of statement text for bank-statement-specific red flags — mathematical consistency, transaction patterns, formatting conventions, and expected spending behaviour.',
    checks: [
      {
        name: 'Running Balance Math Verification',
        detail: 'Extracts lines containing three consecutive numeric values and verifies that the third equals the sum or difference of the first two (debit/credit → new balance). Two or more failures indicate manually altered figures.',
        severity: 'high',
      },
      {
        name: 'Multiple Different Account Numbers',
        detail: 'Searches for account number patterns near keywords like "Account No." across all pages. More than one distinct number in a single statement indicates page-swapping or composite assembly.',
        severity: 'high',
      },
      {
        name: 'Account Holder Name Inconsistency',
        detail: 'Extracts customer name fields from each page individually. Different names on different pages strongly indicate page-swapping — replacing pages from a genuine statement with forged ones.',
        severity: 'high',
      },
      {
        name: 'Sample / Draft Watermark Text',
        detail: 'Regex search for keywords: SAMPLE, DRAFT, VOID, SPECIMEN, TEST. Their presence indicates a template document being passed off as genuine.',
        severity: 'high',
      },
      {
        name: 'Benford\'s Law Violation',
        detail: 'Applies Benford\'s Law (logarithmic first-digit distribution) to all transaction amounts ≥ $10. Genuine financial data closely follows this distribution; manually invented figures deviate because humans unconsciously over-use mid-range digits (5–7) and avoid 1. Three or more deviating digits trigger a high-severity flag.',
        severity: 'high',
      },
      {
        name: 'Exact Duplicate Transaction Rows',
        detail: 'Identifies transaction lines that appear verbatim 3+ times. Bank-generated statements never repeat identical rows — copy-paste fabrication leaves this forensic trace.',
        severity: 'high',
      },
      {
        name: 'Out-of-Order Transaction Dates',
        detail: 'Parses dates from all transaction rows and checks for chronological inversions. Genuine statements list transactions in strict date order; out-of-sequence entries indicate rows were inserted after generation.',
        severity: 'high',
      },
      {
        name: 'Opening / Closing Balance Mismatch Across Pages',
        detail: 'Verifies that the closing balance printed at the bottom of page N matches the opening balance at the top of page N+1. Any mismatch proves pages were taken from different statements and spliced together.',
        severity: 'high',
      },
      {
        name: 'Suspiciously Round Transaction Amounts',
        detail: 'When over 70% of monetary values are perfectly divisible by 100 (e.g. $1,000.00, $5,000.00), the distribution is inconsistent with organic everyday spending.',
        severity: 'medium',
      },
      {
        name: 'Identical Deposit Amounts Repeated',
        detail: 'Flags amounts ≥ $500 that appear 4+ times identically. While a single recurring salary is expected, multiple large identical values suggest fabricated data.',
        severity: 'medium',
      },
      {
        name: 'No Everyday Expense Categories',
        detail: 'Checks for ~30 keywords across groceries, utilities, fuel, dining, subscriptions, and rent. A personal account with no everyday expenses is highly abnormal.',
        severity: 'medium',
      },
      {
        name: 'Multiple Weekend Transactions',
        detail: 'Parses all date patterns and checks for Saturday/Sunday. ACH, wire, and direct deposit do not process on weekends — more than 3 such transactions indicates backdated or fabricated entries.',
        severity: 'medium',
      },
      {
        name: 'Transactions on Bank Holidays',
        detail: 'Flags transaction dates matching known US federal bank holidays (New Year, Independence Day, Thanksgiving, Christmas, Veterans Day). Banks do not post transfers on these dates.',
        severity: 'medium',
      },
      {
        name: 'Generic Transaction Descriptions',
        detail: 'When ≥60% of deposit/credit lines use vague labels ("DEPOSIT", "TRANSFER IN") with no specific employer or sender name, it suggests fabricated income entries.',
        severity: 'medium',
      },
      {
        name: 'Inconsistent Currency Formatting',
        detail: 'Detects amounts with non-standard decimal grouping (e.g. $1,23 instead of $1,234.00) — a sign that values were sourced from a different locale or copy-pasted from a foreign document.',
        severity: 'medium',
      },
      {
        name: 'Misaligned Column Formatting',
        detail: 'Measures the character position of the rightmost decimal point on each transaction row. If more than 30% of rows deviate >15 characters from the mean, columns are misaligned — a sign of manual value editing.',
        severity: 'medium',
      },
      {
        name: 'Suspiciously Uniform Transaction Intervals',
        detail: 'Computes the coefficient of variation (std dev / mean) of gaps between unique transaction dates. A CV below 0.15 across 8+ intervals means transactions are spaced too evenly — real spending is irregular; fabricated dates are often assigned at regular intervals.',
        severity: 'medium',
      },
      {
        name: 'Implausible Income-to-Expense Ratio',
        detail: 'Sums all credit-side and debit-side amounts identified by directional keywords. A ratio above 15× (credits vastly exceed debits) with total credits >$5,000 suggests the statement was fabricated to inflate income while omitting realistic daily outflows.',
        severity: 'medium',
      },
      {
        name: 'Near-Duplicate Transactions Detected',
        detail: 'Strips leading date tokens from transaction rows and counts repeats. The same amount and description appearing 3+ times across different dates may indicate templated fabrication.',
        severity: 'medium',
      },
      {
        name: 'Very Few Everyday Expense Categories',
        detail: 'A softer variant of the expense check: 1–2 recognised expense categories found triggers a low-severity flag rather than medium.',
        severity: 'low',
      },
    ],
  },
]

// ── Derived data ────────────────────────────────────────────────────────────

const UNIVERSAL = ALGORITHMS.filter((a) => a.category === 'universal')
const CONTENT   = ALGORITHMS.filter((a) => a.category === 'content')

const severityLabel: Record<string, string> = {
  high: 'High', medium: 'Medium', low: 'Low',
}

const severityStyle: Record<string, string> = {
  high:   'bg-red-50 text-red-700 border border-red-200',
  medium: 'bg-yellow-50 text-yellow-700 border border-yellow-200',
  low:    'bg-blue-50 text-blue-700 border border-blue-200',
}

const moduleIcon: Record<string, React.ReactNode> = {
  metadata:    <FileSearch size={16} />,
  fonts:       <Type size={16} />,
  text_layers: <Layers size={16} />,
  images:      <Image size={16} />,
  structure:   <Binary size={16} />,
  annotations: <StickyNote size={16} />,
  financial:   <TrendingUp size={16} />,
}

// ── Sub-components ──────────────────────────────────────────────────────────

function SummaryTile({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) {
  return (
    <div className="bg-white rounded border border-[#e0e0e0] px-4 py-3">
      <p className="text-[10px] text-[#888888] uppercase tracking-wider">{label}</p>
      <p className={`text-2xl font-bold mt-0.5 ${accent ? 'text-[#C8102E]' : 'text-[#333333]'}`}>{value}</p>
    </div>
  )
}

interface CategorySectionProps {
  label: string
  sublabel: string
  algorithms: Algorithm[]
  expanded: Record<string, boolean>
  onToggle: (id: string) => void
}

function CategorySection({ label, sublabel, algorithms, expanded, onToggle }: CategorySectionProps) {
  const totalChecks = algorithms.reduce((s, a) => s + a.checks.length, 0)
  return (
    <div>
      {/* Category header */}
      <div className="flex items-center gap-3 mb-3">
        <div>
          <h2 className="text-sm font-bold text-[#333333]">{label}</h2>
          <p className="text-xs text-[#888888]">{sublabel} · {algorithms.length} module{algorithms.length !== 1 ? 's' : ''} · {totalChecks} checks</p>
        </div>
      </div>

      {/* Algorithm cards */}
      <div className="space-y-2">
        {algorithms.map((algo) => {
          const isOpen = !!expanded[algo.id]
          const highCount = algo.checks.filter((c) => c.severity === 'high').length
          const medCount  = algo.checks.filter((c) => c.severity === 'medium').length
          const lowCount  = algo.checks.filter((c) => c.severity === 'low').length

          return (
            <div key={algo.id} className="bg-white rounded border border-[#e0e0e0] overflow-hidden">
              <button
                className="w-full flex items-start gap-3 px-5 py-4 text-left hover:bg-[#fafafa] transition-colors"
                onClick={() => onToggle(algo.id)}
              >
                <div className="w-8 h-8 rounded-full bg-[#C8102E] flex items-center justify-center text-white flex-shrink-0 mt-0.5">
                  {moduleIcon[algo.id]}
                </div>

                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-sm font-semibold text-[#333333]">{algo.name}</span>
                    <span className="text-[11px] text-[#888888]">{algo.checks.length} check{algo.checks.length !== 1 ? 's' : ''}</span>
                  </div>
                  <p className="text-xs text-[#666666] mt-0.5 leading-relaxed pr-4">
                    {algo.description}
                  </p>
                  <div className="flex items-center gap-1.5 mt-2 flex-wrap">
                    {highCount > 0 && (
                      <span className="text-[11px] px-2 py-0.5 rounded bg-red-50 text-red-700 border border-red-200 font-medium">
                        {highCount} High
                      </span>
                    )}
                    {medCount > 0 && (
                      <span className="text-[11px] px-2 py-0.5 rounded bg-yellow-50 text-yellow-700 border border-yellow-200 font-medium">
                        {medCount} Medium
                      </span>
                    )}
                    {lowCount > 0 && (
                      <span className="text-[11px] px-2 py-0.5 rounded bg-blue-50 text-blue-700 border border-blue-200 font-medium">
                        {lowCount} Low
                      </span>
                    )}
                  </div>
                </div>

                <div className="text-[#888888] flex-shrink-0 mt-1">
                  {isOpen ? <ChevronUp size={15} /> : <ChevronDown size={15} />}
                </div>
              </button>

              {isOpen && (
                <div className="border-t border-[#e8e8e8]">
                  {algo.checks.map((check, i) => (
                    <div
                      key={i}
                      className={`px-5 py-3.5 flex items-start gap-3 ${
                        i < algo.checks.length - 1 ? 'border-b border-[#f0f0f0]' : ''
                      } ${i % 2 === 0 ? 'bg-white' : 'bg-[#fafafa]'}`}
                    >
                      <div className="flex-shrink-0 mt-0.5 pl-11">
                        <span className={`text-[11px] px-2 py-0.5 rounded font-medium whitespace-nowrap ${severityStyle[check.severity]}`}>
                          {severityLabel[check.severity]}
                        </span>
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-xs font-semibold text-[#333333]">{check.name}</p>
                        <p className="text-xs text-[#666666] mt-0.5 leading-relaxed">{check.detail}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ── Page ────────────────────────────────────────────────────────────────────

export function SettingsPage() {
  const [expanded, setExpanded] = useState<Record<string, boolean>>({})
  const toggle = (id: string) => setExpanded((prev) => ({ ...prev, [id]: !prev[id] }))

  const allChecks   = ALGORITHMS.flatMap((a) => a.checks)
  const totalChecks = allChecks.length
  const highChecks  = allChecks.filter((c) => c.severity === 'high').length
  const universalChecks = UNIVERSAL.reduce((s, a) => s + a.checks.length, 0)
  const contentChecks   = CONTENT.reduce((s, a)   => s + a.checks.length, 0)

  return (
    <div className="flex-1 overflow-y-auto bg-[#f5f5f5] p-6">
      <div className="max-w-3xl mx-auto">

        {/* Page header */}
        <div className="mb-6">
          <h1 className="text-xl font-bold text-[#333333]">Detection Algorithm Details</h1>
          <p className="text-sm text-[#666666] mt-1">
            All fraud detection checks performed on each uploaded document, organised into two tiers.
          </p>
        </div>

        {/* Summary tiles */}
        <div className="grid grid-cols-4 gap-3 mb-8">
          <SummaryTile label="Total Modules"        value={String(ALGORITHMS.length)} />
          <SummaryTile label="Total Checks"         value={String(totalChecks)} />
          <SummaryTile label="High-Severity Checks" value={String(highChecks)} accent />
          <SummaryTile label="Universal / Content"  value={`${universalChecks} / ${contentChecks}`} />
        </div>

        {/* Two-tier layout */}
        <div className="space-y-8">

          {/* Part I */}
          <div className="rounded-lg border border-[#d6d6d6] overflow-hidden">
            <div className="px-5 py-3 bg-[#1a1a2e] flex items-center gap-2">
              <Database size={14} className="text-[#a0a8c0]" />
              <span className="text-xs font-bold text-white tracking-wide uppercase">
                Part I — Universal Checks
              </span>
              <span className="ml-auto text-[11px] text-[#a0a8c0]">
                Applies to any PDF document type
              </span>
            </div>
            <div className="p-4 bg-[#f5f5f5]">
              <CategorySection
                label="Universal (Non-Content-Based)"
                sublabel="Inspects the PDF container — metadata, structure, fonts, images, text layers, annotations"
                algorithms={UNIVERSAL}
                expanded={expanded}
                onToggle={toggle}
              />
            </div>
          </div>

          {/* Part II */}
          <div className="rounded-lg border border-[#d6d6d6] overflow-hidden">
            <div className="px-5 py-3 bg-[#C8102E] flex items-center gap-2">
              <TrendingUp size={14} className="text-white opacity-80" />
              <span className="text-xs font-bold text-white tracking-wide uppercase">
                Part II — Content-Based Checks
              </span>
              <span className="ml-auto text-[11px] text-red-100">
                Bank-statement-specific heuristics
              </span>
            </div>
            <div className="p-4 bg-[#f5f5f5]">
              <CategorySection
                label="Content-Based (Bank Statement Specific)"
                sublabel="Parses extracted text for financial logic errors, implausible patterns, and fabricated data"
                algorithms={CONTENT}
                expanded={expanded}
                onToggle={toggle}
              />
            </div>
          </div>

        </div>

        {/* Footer */}
        <div className="mt-6 px-4 py-3 bg-white rounded border border-[#e0e0e0] flex items-start gap-3">
          <Shield size={14} className="text-[#C8102E] flex-shrink-0 mt-0.5" />
          <p className="text-xs text-[#666666] leading-relaxed">
            All checks run client-side within the analysis engine. No document content is transmitted beyond the local server. Results are cached per document and can be re-triggered at any time.
          </p>
        </div>

      </div>
    </div>
  )
}
